User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'DeprecatePythonPath - control'
> conda --version
> pyenv root
> python3.7 c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2021-10-16 09:44:02: Detection of Python Interpreter for Command python3 and args  failed as file  does not exist
Error 2021-10-16 09:44:02: Failed to get interpreter information for 'C:\Users\InThiruA\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\\Users\InThiruA\AppData\Local\Microsoft\WindowsApps\python3.exe" "c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py" "c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\interpreterInfo.py"
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

	at ChildProcess.exithandler (child_process.js:312:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\InThiruA\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "c:\\வட்டு\\PortableApps\\WPy64-3940\\t\\vscode\\data\\extensions\\ms-python.python-2021.3.680753044\\pythonFiles\\pyvsc-run-isolated.py" "c:\\வட்டு\\PortableApps\\WPy64-3940\\t\\vscode\\data\\extensions\\ms-python.python-2021.3.680753044\\pythonFiles\\interpreterInfo.py"'
}
Error 2021-10-16 09:44:02: Failed to get interpreter information for 'C:\Users\InThiruA\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\\Users\InThiruA\AppData\Local\Microsoft\WindowsApps\python.exe" "c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py" "c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\interpreterInfo.py"
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

	at ChildProcess.exithandler (child_process.js:312:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:443:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\InThiruA\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "c:\\வட்டு\\PortableApps\\WPy64-3940\\t\\vscode\\data\\extensions\\ms-python.python-2021.3.680753044\\pythonFiles\\pyvsc-run-isolated.py" "c:\\வட்டு\\PortableApps\\WPy64-3940\\t\\vscode\\data\\extensions\\ms-python.python-2021.3.680753044\\pythonFiles\\interpreterInfo.py"'
}
Error 2021-10-16 09:44:02: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'd:\G\nitsm-devtools-python\.vscode\settings.json' (Error: Unable to resolve non-existing file 'd:\G\nitsm-devtools-python\.vscode\settings.json')
	at _handleError (c:\வட்டு\PortableApps\WPy64-3940\t\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:154942)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async y.readText (c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:9:328725)
	at async p.doesFileNeedToBeFixed (c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:61:578263)
	at async c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:61:577390
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:61:577336)
	at async p.updateTestSettings (c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:61:576963)] {
  code: 'FileNotFound'
}
Error 2021-10-16 09:44:02: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'c:\Users\InThiruA\AppData\Roaming\Code\User\settings.json' (Error: Unable to resolve non-existing file 'c:\Users\InThiruA\AppData\Roaming\Code\User\settings.json')
	at _handleError (c:\வட்டு\PortableApps\WPy64-3940\t\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:154942)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async y.readText (c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:9:328725)
	at async p.doesFileNeedToBeFixed (c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:61:578263)
	at async c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:61:577390
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:61:577336)
	at async p.updateTestSettings (c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:61:576963)] {
  code: 'FileNotFound'
}
Python interpreter path: C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe
Starting Jedi Python language engine.
> pyenv root
> pyenv root
> conda --version
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_nidigital.py
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_nidigital.py
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py site --user-site
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py site --user-site
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_niscope.py
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_niscope.py
cwd: d:\G\nitsm-devtools-python
Error 2021-10-16 09:44:51: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

##########Linting Output - pylint##########
************* Module test_niscope
4,0,error,import-error:Unable to import 'niscope'
5,0,error,import-error:Unable to import 'nitsm.codemoduleapi'
6,0,error,import-error:Unable to import 'nitsm.codemoduleapi'
7,0,error,import-error:Unable to import 'scope'

-----------------------------------
Your code has been rated at 6.88/10

Error 2021-10-16 09:44:54: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

Error 2021-10-16 09:44:54: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(

Error 2021-10-16 09:44:54: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(

Error 2021-10-16 09:44:54: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:626: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

##########Linting Output - pylint##########
************* Module test_nidigital
6,0,error,import-error:Unable to import 'digital'
7,0,error,import-error:Unable to import 'nitsm.codemoduleapi'
8,0,error,import-error:Unable to import 'nidigital'
9,0,error,import-error:Unable to import 'nidigital.history_ram_cycle_information'
10,0,error,import-error:Unable to import 'nitsm.codemoduleapi'

-----------------------------------
Your code has been rated at 8.84/10

> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_nidigital.py
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_nidigital.py
cwd: d:\G\nitsm-devtools-python
Error 2021-10-16 09:45:05: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

##########Linting Output - pylint##########
************* Module test_nidigital
6,0,error,import-error:Unable to import 'digital'
7,0,error,import-error:Unable to import 'nitsm.codemoduleapi'
8,0,error,import-error:Unable to import 'nidigital'
9,0,error,import-error:Unable to import 'nidigital.history_ram_cycle_information'
10,0,error,import-error:Unable to import 'nitsm.codemoduleapi'

------------------------------------------------------------------
Your code has been rated at 8.84/10 (previous run: 8.84/10, +0.00)

Error 2021-10-16 09:45:21: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(

Error 2021-10-16 09:45:21: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(

Error 2021-10-16 09:45:21: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:626: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

Error 2021-10-16 09:45:40: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(

Error 2021-10-16 09:45:40: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(

Error 2021-10-16 09:45:40: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:626: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

Error 2021-10-16 09:46:59: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(

Error 2021-10-16 09:46:59: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(

Error 2021-10-16 09:46:59: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:626: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

Error 2021-10-16 09:47:00: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(

Error 2021-10-16 09:47:00: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(

Error 2021-10-16 09:47:00: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:626: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

Error 2021-10-16 09:47:15: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:603: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).goto instead.
  script.goto_assignments(follow_imports=True), request["id"]

> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_niscope.py
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_niscope.py
cwd: d:\G\nitsm-devtools-python
Error 2021-10-16 10:02:30: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

##########Linting Output - pylint##########
************* Module test_niscope
4,0,error,import-error:Unable to import 'niscope'
5,0,error,import-error:Unable to import 'nitsm.codemoduleapi'
6,0,error,import-error:Unable to import 'nitsm.codemoduleapi'
7,0,error,import-error:Unable to import 'scope'

------------------------------------------------------------------
Your code has been rated at 6.88/10 (previous run: 6.88/10, +0.00)

Error 2021-10-16 10:32:57: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(

Error 2021-10-16 10:32:57: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:592: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(

Error 2021-10-16 10:32:58: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:626: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_nidigital.py
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_nidigital.py
cwd: d:\G\nitsm-devtools-python
Error 2021-10-16 10:33:26: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_niscope.py
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_niscope.py
cwd: d:\G\nitsm-devtools-python
##########Linting Output - pylint##########
************* Module test_nidigital
6,0,error,import-error:Unable to import 'digital'
7,0,error,import-error:Unable to import 'nitsm.codemoduleapi'
8,0,error,import-error:Unable to import 'nidigital'
9,0,error,import-error:Unable to import 'nidigital.history_ram_cycle_information'
10,0,error,import-error:Unable to import 'nitsm.codemoduleapi'

------------------------------------------------------------------
Your code has been rated at 8.84/10 (previous run: 8.84/10, +0.00)

Error 2021-10-16 10:33:30: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

##########Linting Output - pylint##########
************* Module test_niscope
4,0,error,import-error:Unable to import 'niscope'
5,0,error,import-error:Unable to import 'nitsm.codemoduleapi'
6,0,error,import-error:Unable to import 'nitsm.codemoduleapi'
7,0,error,import-error:Unable to import 'scope'

------------------------------------------------------------------
Your code has been rated at 6.88/10 (previous run: 6.88/10, +0.00)

> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_nidigital.py
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_nidigital.py
cwd: d:\G\nitsm-devtools-python
Error 2021-10-16 10:33:37: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

##########Linting Output - pylint##########
************* Module test_nidigital
6,0,error,import-error:Unable to import 'digital'
7,0,error,import-error:Unable to import 'nitsm.codemoduleapi'
8,0,error,import-error:Unable to import 'nidigital'
9,0,error,import-error:Unable to import 'nidigital.history_ram_cycle_information'
10,0,error,import-error:Unable to import 'nitsm.codemoduleapi'

------------------------------------------------------------------
Your code has been rated at 8.84/10 (previous run: 8.84/10, +0.00)

> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_dcpower.py
cwd: d:\G\nitsm-devtools-python
> C:\வட்டு\PortableApps\WPy64-3940\python-3.9.4.amd64\python.exe c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\G\nitsm-devtools-python\tests\test_dcpower.py
cwd: d:\G\nitsm-devtools-python
Error 2021-10-16 10:33:46: stderr jediProxy Error (stderr) c:\வட்டு\PortableApps\WPy64-3940\t\vscode\data\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

##########Linting Output - pylint##########
************* Module test_dcpower
2,0,error,import-error:Unable to import 'nidcpower'
3,0,error,import-error:Unable to import 'nidevtools.dcpower'
35,4,error,no-self-argument:Method should have "self" as first argument
36,8,error,no-member:Instance of 'TestDCPower' has no 'query_in_compliance' member

------------------------------------
Your code has been rated at -4.29/10

